name: bass_boost
description: A flutter plugin to control the bass of any audio that is playing in the android device using the  audioSessionId of the playing audio.
version: 0.1.1
author: Aman Malhotra <official.aman18@gmail.com>
homepage: https://github.com/aman-malhotra-1999/Bass-Boost-Flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.amanmalhotra.bassboost
    pluginClass: BassBoostPlugin
